# Generated by Django 6.0.5 on 2026-06-22 01:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('removed', models.BooleanField(default=False, verbose_name='removed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
